/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as SpectralRouteImport } from './routes/spectral'
import { Route as StorageRouteImport } from './routes/storage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectralRoute = SpectralRouteImport.update({
  id: '/spectral',
  path: '/spectral',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/ledger': typeof LedgerRoute
  '/manifesto': typeof ManifestoRoute
  '/mesh': typeof MeshRoute
  '/spectral': typeof SpectralRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/ledger': typeof LedgerRoute
  '/manifesto': typeof ManifestoRoute
  '/mesh': typeof MeshRoute
  '/spectral': typeof SpectralRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hardware': typeof HardwareRoute
  '/ledger': typeof LedgerRoute
  '/manifesto': typeof ManifestoRoute
  '/mesh': typeof MeshRoute
  '/spectral': typeof SpectralRoute
  '/storage': typeof StorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hardware'
    | '/ledger'
    | '/manifesto'
    | '/mesh'
    | '/spectral'
    | '/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hardware'
    | '/ledger'
    | '/manifesto'
    | '/mesh'
    | '/spectral'
    | '/storage'
  id:
    | '__root__'
    | '/'
    | '/hardware'
    | '/ledger'
    | '/manifesto'
    | '/mesh'
    | '/spectral'
    | '/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HardwareRoute: typeof HardwareRoute
  LedgerRoute: typeof LedgerRoute
  ManifestoRoute: typeof ManifestoRoute
  MeshRoute: typeof MeshRoute
  SpectralRoute: typeof SpectralRoute
  StorageRoute: typeof StorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectral': {
      id: '/spectral'
      path: '/spectral'
      fullPath: '/spectral'
      preLoaderRoute: typeof SpectralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HardwareRoute: HardwareRoute,
  LedgerRoute: LedgerRoute,
  ManifestoRoute: ManifestoRoute,
  MeshRoute: MeshRoute,
  SpectralRoute: SpectralRoute,
  StorageRoute: StorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
